SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3 # seconds

SHOT_RADIUS = 5

POWERUP_SPAWN_RATE = 1 # seconds

POWERUP_RADIUS = 15
POWERUPS = ["SPEED", "MULTI_SHOT", "FIRE_RATE"]

POWERUP_SPEED_INC_RATE = 20
POWERUP_RATE_OF_FIRE_INC = .01

POWERUP_MAX_SPEED = 5
POWERUP_MAX_RATE_OF_FIRE = 10
POWERUP_MAX_MULTI_SHOT_= 3